name: bellsmkncampalagian
version: 12.0.0
publish_to: none
description: Sistem Bell Sekolah pada SMKN Campalagian
environment:
  sdk: ">3.5.3"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.1.1
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  audioplayers: ^6.1.0
  intl: ^0.20.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/sound/
    - assets/sound/lagu_nasional/
  uses-material-design: true
